CXX = g++
CSTD = -std=c++14
CLASS_TELEPHONE_NUMBER = telephone_number
CLASS_CONTACT = contact
CLASS_SMS = sms
CLASS_UTILS_STRING = utils_string
CLASS_UTILS_FILE_SYSTEM = utils_file_system
CLASS_UTILS_HTML = utils_html
CLASS_EXEC_CONTACTS_AND_SMS_REPORTS = exec_contacts_and_sms_reports
CLASS_GUI_CONTACTS_AND_SMS_REPORTS = gui_contacts_and_sms_reports
FILE_EXT_INCLUDE = hpp
FILE_EXT_SRC = cpp
FILE_EXT_BUILD = o
MAIN = main
EXE = contacts_and_sms_reports
BUILD_DEBUG = debug
BUILD_RELEASE = release
PATH_INCLUDE = ./include
PATH_SRC = ./src
PATH_BUILD_ROOT = ./build
PATH_BUILD_DEBUG = $(PATH_BUILD_ROOT)/$(BUILD_DEBUG)
PATH_BUILD_RELEASE = $(PATH_BUILD_ROOT)/$(BUILD_RELEASE)
PATH_LIB =./lib
PATH_BIN_ROOT = ./bin
PATH_BIN_DEBUG = $(PATH_BIN_ROOT)/$(BUILD_DEBUG)
PATH_BIN_RELEASE = $(PATH_BIN_ROOT)/$(BUILD_RELEASE)

##
# Default build mode when no targets
##

BUILD_MODE = $(BUILD_DEBUG)
CFLAGS = $(CSTD) -Wall -g3
PATH_BUILD = $(PATH_BUILD_DEBUG)
PATH_BIN = $(PATH_BIN_DEBUG)

###

ifeq ($(MAKECMDGOALS),$(BUILD_RELEASE))
	BUILD_MODE = $(BUILD_RELEASE)
	CFLAGS = $(CSTD) -O
	PATH_BUILD = $(PATH_BUILD_RELEASE)
	PATH_BIN = $(PATH_BIN_RELEASE)
endif

$(BUILD_DEBUG) $(BUILD_RELEASE): pre_build $(PATH_BUILD) $(PATH_BIN) $(EXE)

pre_build:
	@echo Building $(BUILD_MODE) mode...

$(PATH_BUILD):
	mkdir -p -m 755 $(PATH_BUILD)

$(PATH_BIN):
	mkdir -p -m 755 $(PATH_BIN)

$(EXE): $(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD) $(CLASS_SMS).$(FILE_EXT_BUILD) \
	$(CLASS_CONTACT).$(FILE_EXT_BUILD) $(CLASS_UTILS_STRING).$(FILE_EXT_BUILD) \
	$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD) $(CLASS_UTILS_HTML).$(FILE_EXT_BUILD) \
	$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD)

	$(CXX) $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_BUILD)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_CONTACT).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_SMS).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(PATH_SRC)/$(MAIN).$(FILE_EXT_SRC) -o $(PATH_BIN)/$(EXE) \
	`pkg-config gtkmm-3.0 --cflags --libs`

$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_SRC) -o \
    $(PATH_BUILD)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD)

$(CLASS_SMS).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_SMS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_SMS).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_SMS).$(FILE_EXT_BUILD)

$(CLASS_CONTACT).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_CONTACT).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_CONTACT).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_CONTACT).$(FILE_EXT_BUILD)

$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_UTILS_STRING).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_UTILS_STRING).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD)

$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD)

$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_UTILS_HTML).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_UTILS_HTML).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD)

$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD)

$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	`pkg-config gtkmm-3.0 --cflags --libs`

clean:
	rm -Rf $(PATH_BUILD_ROOT) $(PATH_BIN_ROOT)
