CXX = g++
CFLAGS = -std=c++11 -Wall -g3
PATH_INCLUDE = ./include
PATH_SRC = ./src
PATH_BUILD = ./build
PATH_LIB =./lib
PATH_BIN = ./bin
CLASS_TELEPHONE_NUMBER = telephone_number
CLASS_CONTACT = contact
CLASS_SMS = sms
CLASS_UTILS_STRING = utils_string
CLASS_UTILS_FILE_SYSTEM = utils_file_system
CLASS_UTILS_HTML = utils_html
CLASS_EXEC_CONTACTS_AND_SMS_REPORTS = exec_contacts_and_sms_reports
CLASS_GUI_CONTACTS_AND_SMS_REPORTS = gui_contacts_and_sms_reports
FILE_EXT_INCLUDE = hpp
FILE_EXT_SRC = cpp
FILE_EXT_BUILD = o
MAIN = main
EXE = contacts_and_sms_reports

all: debug

debug: $(PATH_BUILD)/debug $(PATH_BIN)/debug $(EXE)
	mv $(PATH_BUILD)/*.$(FILE_EXT_BUILD) $(PATH_BUILD)/debug/
	mv $(PATH_BIN)/$(EXE) $(PATH_BIN)/debug/

release: $(PATH_BUILD)/release $(PATH_BIN)/release $(EXE)
	mv $(PATH_BUILD)/*.$(FILE_EXT_BUILD) $(PATH_BUILD)/release/
	mv $(PATH_BIN)/$(EXE) $(PATH_BIN)/release/

$(PATH_BUILD)/debug:
	mkdir -p -m 755 $(PATH_BUILD)/debug

$(PATH_BIN)/debug:
	mkdir -p -m 755 $(PATH_BIN)/debug

$(PATH_BUILD)/release:
	mkdir -p -m 755 $(PATH_BUILD)/release

$(PATH_BIN)/release:
	mkdir -p -m 755 $(PATH_BIN)/release

$(EXE): $(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD) $(CLASS_SMS).$(FILE_EXT_BUILD) \
	$(CLASS_CONTACT).$(FILE_EXT_BUILD) $(CLASS_UTILS_STRING).$(FILE_EXT_BUILD) \
	$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD) $(CLASS_UTILS_HTML).$(FILE_EXT_BUILD) \
	$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD)

	$(CXX) $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_BUILD)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_CONTACT).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_SMS).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(PATH_BUILD)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	$(PATH_SRC)/$(MAIN).$(FILE_EXT_SRC) -o $(PATH_BIN)/$(EXE) \
	`pkg-config gtkmm-3.0 --cflags --libs`

$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_SRC) -o \
    $(PATH_BUILD)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_BUILD)

$(CLASS_SMS).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_SMS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_SMS).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_SMS).$(FILE_EXT_BUILD)

$(CLASS_CONTACT).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_CONTACT).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_CONTACT).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_CONTACT).$(FILE_EXT_BUILD)

$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD): $(PATH_SRC)/$(CLASS_UTILS_STRING).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) $(PATH_SRC)/$(CLASS_UTILS_STRING).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_UTILS_STRING).$(FILE_EXT_BUILD)

$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE)
	
	$(CXX) -c $(CFLAGS) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_BUILD)

$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_UTILS_HTML).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_UTILS_HTML).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_UTILS_HTML).$(FILE_EXT_BUILD)

$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	-o $(PATH_BUILD)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD)

$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD): \
	$(PATH_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) \
	$(PATH_INCLUDE)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_SMS).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_CONTACT).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_STRING).$(FILE_EXT_INCLUDE) \
	$(PATH_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).$(FILE_EXT_INCLUDE) \
	$(PATH_LIB)/CTML.h $(PATH_INCLUDE)/$(CLASS_UTILS_HTML).$(FILE_EXT_INCLUDE)

	$(CXX) -c $(CFLAGS) -I$(PATH_LIB) -I$(PATH_INCLUDE) \
	$(PATH_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_SRC) -o \
	$(PATH_BUILD)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).$(FILE_EXT_BUILD) \
	`pkg-config gtkmm-3.0 --cflags --libs`

clean:
	rm -Rf $(PATH_BUILD) $(PATH_BIN)
