CXX = g++
CPPFLAGS = -Wall -g
PATH_CLASSES = ./classes
PATH_CLASSES_INCLUDE = $(PATH_CLASSES)/include
PATH_CLASSES_SRC = $(PATH_CLASSES)/src
PATH_CLASSES_OBJ = $(PATH_CLASSES)/obj
PATH_LIBS=./libraries
PATH_LIB_CTML=$(PATH_LIBS)/CTML
CLASS_TELEPHONE_NUMBER = telephone_number
CLASS_CONTACT = contact
CLASS_SMS = sms
CLASS_UTILS_HTML = utils_html
CLASS_UTILS_FILE_SYSTEM = utils_file_system
CLASS_EXEC_CONTACTS_AND_SMS_REPORTS = exec_contacts_and_sms_reports
CLASS_GUI_CONTACTS_AND_SMS_REPORTS = gui_contacts_and_sms_reports
MAIN = main
EXE = contacts_and_sms_reports

all: $(PATH_CLASSES_OBJ) $(EXE)

$(PATH_CLASSES_OBJ):
	mkdir -m 755 $(PATH_CLASSES_OBJ)

$(EXE): $(MAIN).cpp $(CLASS_TELEPHONE_NUMBER).o $(CLASS_CONTACT).o $(CLASS_SMS).o $(CLASS_UTILS_HTML).o \
	$(CLASS_UTILS_FILE_SYSTEM).o $(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).o \
	$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).o

	$(CXX) $(CPPFLAGS) -I$(PATH_LIB_CTML) -I$(PATH_CLASSES_INCLUDE) \
	$(PATH_CLASSES_OBJ)/$(CLASS_TELEPHONE_NUMBER).o $(PATH_CLASSES_OBJ)/$(CLASS_CONTACT).o \
	$(PATH_CLASSES_OBJ)/$(CLASS_SMS).o $(PATH_CLASSES_OBJ)/$(CLASS_UTILS_HTML).o \
	$(PATH_CLASSES_OBJ)/$(CLASS_UTILS_FILE_SYSTEM).o \
	$(PATH_CLASSES_OBJ)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).o \
	$(PATH_CLASSES_OBJ)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).o $(MAIN).cpp -o $(EXE) \
	`pkg-config gtkmm-3.0 --cflags --libs`

$(CLASS_TELEPHONE_NUMBER).o: $(PATH_CLASSES_SRC)/$(CLASS_TELEPHONE_NUMBER).cpp \
	$(PATH_CLASSES_INCLUDE)/$(CLASS_TELEPHONE_NUMBER).h
	
	$(CXX) -c $(CPPFLAGS) -I$(PATH_CLASSES_INCLUDE) $(PATH_CLASSES_SRC)/$(CLASS_TELEPHONE_NUMBER).cpp -o \
    $(PATH_CLASSES_OBJ)/$(CLASS_TELEPHONE_NUMBER).o

$(CLASS_CONTACT).o: $(PATH_CLASSES_SRC)/$(CLASS_CONTACT).cpp $(PATH_CLASSES_INCLUDE)/$(CLASS_CONTACT).h
	$(CXX) -c $(CPPFLAGS) -I$(PATH_CLASSES_INCLUDE) $(PATH_CLASSES_SRC)/$(CLASS_CONTACT).cpp -o \
	$(PATH_CLASSES_OBJ)/$(CLASS_CONTACT).o

$(CLASS_SMS).o: $(PATH_CLASSES_SRC)/$(CLASS_SMS).cpp $(PATH_CLASSES_INCLUDE)/$(CLASS_SMS).h
	$(CXX) -c $(CPPFLAGS) -I$(PATH_CLASSES_INCLUDE) $(PATH_CLASSES_SRC)/$(CLASS_SMS).cpp -o \
	$(PATH_CLASSES_OBJ)/$(CLASS_SMS).o

$(CLASS_UTILS_HTML).o: $(PATH_CLASSES_SRC)/$(CLASS_UTILS_HTML).cpp \
	$(PATH_CLASSES_INCLUDE)/$(CLASS_UTILS_HTML).h $(PATH_LIB_CTML)/CTML.h

	$(CXX) -c $(CPPFLAGS) -I$(PATH_LIB_CTML) -I$(PATH_CLASSES_INCLUDE) \
	$(PATH_CLASSES_SRC)/$(CLASS_UTILS_HTML).cpp -o $(PATH_CLASSES_OBJ)/$(CLASS_UTILS_HTML).o

$(CLASS_UTILS_FILE_SYSTEM).o: $(PATH_CLASSES_SRC)/$(CLASS_UTILS_FILE_SYSTEM).cpp \
	$(PATH_CLASSES_INCLUDE)/$(CLASS_UTILS_FILE_SYSTEM).h
	
	$(CXX) -c $(CPPFLAGS) -I$(PATH_CLASSES_INCLUDE) $(PATH_CLASSES_SRC)/$(CLASS_UTILS_FILE_SYSTEM).cpp \
	-o $(PATH_CLASSES_OBJ)/$(CLASS_UTILS_FILE_SYSTEM).o

$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).o: $(PATH_CLASSES_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).cpp \
	$(PATH_CLASSES_INCLUDE)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).h

	$(CXX) -c $(CPPFLAGS) -I$(PATH_LIB_CTML) -I$(PATH_CLASSES_INCLUDE) \
	$(PATH_CLASSES_SRC)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).cpp \
	-o $(PATH_CLASSES_OBJ)/$(CLASS_EXEC_CONTACTS_AND_SMS_REPORTS).o

$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).o: $(PATH_CLASSES_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).cpp \
	$(PATH_CLASSES_INCLUDE)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).h

	$(CXX) -c $(CPPFLAGS) -I$(PATH_LIB_CTML) -I$(PATH_CLASSES_INCLUDE) \
	$(PATH_CLASSES_SRC)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).cpp -o \
	$(PATH_CLASSES_OBJ)/$(CLASS_GUI_CONTACTS_AND_SMS_REPORTS).o `pkg-config gtkmm-3.0 --cflags --libs`

clean:
	rm -Rf $(EXE) $(PATH_CLASSES_OBJ)
